In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
from google.colab import files
files.upload()

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d sumanbera19/bengaluru-house-price-dataset

Dataset URL: https://www.kaggle.com/datasets/sumanbera19/bengaluru-house-price-dataset
License(s): CC0-1.0
Downloading bengaluru-house-price-dataset.zip to /content
100% 194k/194k [00:00<00:00, 82.4MB/s]

In [ ]:
import zipfile

In [ ]:
with zipfile.ZipFile("bengaluru-house-price-dataset.zip") as z:
  z.extractall("House")

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/House/bengaluru_house_prices.csv")
df=pd.DataFrame(data)
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [ ]:
df.isnull().sum().sum()

np.int64(6201)

In [ ]:
df.size

119880

In [ ]:
df1_1=df.dropna()
df1_1.size

67464

In [ ]:
df_2=df.fillna(100)
df_2.size

119880

In [ ]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [ ]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [ ]:
df.shape

(13320, 9)

In [ ]:
a=df.isnull().sum()/df.shape[0]*100
a

area_type        0.000000
availability     0.000000
location         0.007508
size             0.120120
society         41.306306
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
dtype: float64

In [ ]:
b=a[a>17].keys()
b

Index(['society'], dtype='object')

In [ ]:
df.drop(b,axis=1,inplace=True)

In [ ]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [ ]:
df.isnull().sum()

area_type         0
availability      0
location          1
size             16
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [ ]:
cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

['area_type', 'availability', 'location', 'size', 'total_sqft']

In [ ]:
num_col=df.select_dtypes(include=["int64","float64"]).columns.tolist()
num_col

['bath', 'balcony', 'price']

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
cat_clean=SimpleImputer(strategy="most_frequent")
num_clean=SimpleImputer(strategy="mean")

In [ ]:
df[cat_col]=cat_clean.fit_transform(df[cat_col])
df[num_col]=num_clean.fit_transform(df[num_col])

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.size

106560

In [ ]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.000000,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.000000,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.000000,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.000000,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.000000,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.000000,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,1.584376,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.000000,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.000000,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.000000,17.00

In [ ]:
df['price']=df['price']*100000
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.000000,3907000.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.000000,12000000.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.000000,6200000.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.000000,9500000.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.000000,5100000.0
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.000000,23100000.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,1.584376,40000000.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.000000,6000000.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.000000,48800000.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.000000,1700000.0

In [ ]:
print("2 BHK")

2 BHK

In [ ]:
a=df['size'].apply(lambda x:int(x.split(" ")[0]))
a

0        2
1        4
2        3
3        3
4        2
        ..
13315    5
13316    4
13317    2
13318    4
13319    1
Name: size, Length: 13320, dtype: int64

In [ ]:
df.insert(3,"BHK",a)

In [ ]:
df

,area_type,availability,location,BHK,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,2 BHK,1056,2.0,1.000000,3907000.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4,4 Bedroom,2600,5.0,3.000000,12000000.0
2,Built-up Area,Ready To Move,Uttarahalli,3,3 BHK,1440,2.0,3.000000,6200000.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,3 BHK,1521,3.0,1.000000,9500000.0
4,Super built-up Area,Ready To Move,Kothanur,2,2 BHK,1200,2.0,1.000000,5100000.0
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5,5 Bedroom,3453,4.0,0.000000,23100000.0
13316,Super built-up Area,Ready To Move,Richards Town,4,4 BHK,3600,5.0,1.584376,40000000.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,2 BHK,1141,2.0,1.000000,6000000.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4 BHK,4689,4.0,1.000000,48800000.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1,1 BHK,550,1.0,1.000000,1700000.0

In [ ]:
df.drop("size",axis=1,inplace=True)

In [ ]:
df

,area_type,availability,location,BHK,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,1056,2.0,1.000000,3907000.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4,2600,5.0,3.000000,12000000.0
2,Built-up Area,Ready To Move,Uttarahalli,3,1440,2.0,3.000000,6200000.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,1521,3.0,1.000000,9500000.0
4,Super built-up Area,Ready To Move,Kothanur,2,1200,2.0,1.000000,5100000.0
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5,3453,4.0,0.000000,23100000.0
13316,Super built-up Area,Ready To Move,Richards Town,4,3600,5.0,1.584376,40000000.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,1141,2.0,1.000000,6000000.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4689,4.0,1.000000,48800000.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1,550,1.0,1.000000,1700000.0

In [ ]:
df.drop(["area_type","availability"],axis=1,inplace=True)

In [ ]:
df

                       location  BHK total_sqft  bath   balcony       price
0      Electronic City Phase II    2       1056   2.0  1.000000   3907000.0
1              Chikka Tirupathi    4       2600   5.0  3.000000  12000000.0
2                   Uttarahalli    3       1440   2.0  3.000000   6200000.0
3            Lingadheeranahalli    3       1521   3.0  1.000000   9500000.0
4                      Kothanur    2       1200   2.0  1.000000   5100000.0
...                         ...  ...        ...   ...       ...         ...
13315                Whitefield    5       3453   4.0  0.000000  23100000.0
13316             Richards Town    4       3600   5.0  1.584376  40000000.0
13317     Raja Rajeshwari Nagar    2       1141   2.0  1.000000   6000000.0
13318           Padmanabhanagar    4       4689   4.0  1.000000  48800000.0
13319              Doddathoguru    1        550   1.0  1.000000   1700000.0

[13320 rows x 6 columns]

In [ ]:
# df.insert(5,"price/sqft",df["price"]/df['total_sqft'])

In [ ]:
df["price"].dtypes

dtype('float64')

In [ ]:
df['total_sqft'].dtypes

dtype('O')

In [ ]:
def check(x):
  try:
   float(x)
   return True
  except:
    return False

In [ ]:
z=df[~df['total_sqft'].apply(check)]

In [ ]:
z

                 location  BHK   total_sqft     bath   balcony       price
30              Yelahanka    4  2100 - 2850  4.00000  0.000000  18600000.0
56            Devanahalli    4  3010 - 3410  2.69261  1.584376  19200000.0
81            Hennur Road    4  2957 - 3450  2.69261  1.584376  22450000.0
122                Hebbal    4  3067 - 8156  4.00000  0.000000  47700000.0
137    8th Phase JP Nagar    2  1042 - 1105  2.00000  0.000000   5400500.0
...                   ...  ...          ...      ...       ...         ...
12990      Talaghattapura    3  1804 - 2273  3.00000  0.000000  12200000.0
13059              Harlur    2  1200 - 1470  2.00000  0.000000   7276000.0
13240         Devanahalli    1  1020 - 1130  2.69261  1.584376   5257000.0
13265               Hoodi    2  1133 - 1384  2.00000  0.000000   5913500.0
13299          Whitefield    4  2830 - 2882  5.00000  0.000000  15450000.0

[247 rows x 6 columns]

In [ ]:
def convert(x):
  if isinstance(x,str):
    x=x.strip()
    if "-" in x:
      try:
        a,b=x.split("-")
        return (float(a)+float(b))/2
      except:
        return float(x)
    try:
      return float(x)
    except:
      return np.nan
  return np.nan

In [ ]:
df['total_sqft']=df['total_sqft'].apply(convert)

In [ ]:
df.shape

(13320, 6)

In [ ]:
df.isnull().sum()

location       0
BHK            0
total_sqft    46
bath           0
balcony        0
price          0
dtype: int64

In [ ]:
df_1=df.dropna(inplace=True)

In [ ]:
df_1

In [ ]:
df_1

In [ ]:
df

                       location  BHK  total_sqft  bath   balcony       price
0      Electronic City Phase II    2      1056.0   2.0  1.000000   3907000.0
1              Chikka Tirupathi    4      2600.0   5.0  3.000000  12000000.0
2                   Uttarahalli    3      1440.0   2.0  3.000000   6200000.0
3            Lingadheeranahalli    3      1521.0   3.0  1.000000   9500000.0
4                      Kothanur    2      1200.0   2.0  1.000000   5100000.0
...                         ...  ...         ...   ...       ...         ...
13315                Whitefield    5      3453.0   4.0  0.000000  23100000.0
13316             Richards Town    4      3600.0   5.0  1.584376  40000000.0
13317     Raja Rajeshwari Nagar    2      1141.0   2.0  1.000000   6000000.0
13318           Padmanabhanagar    4      4689.0   4.0  1.000000  48800000.0
13319              Doddathoguru    1       550.0   1.0  1.000000   1700000.0

[13274 rows x 6 columns]

In [ ]:
df_2=df.dropna(subset=["total_sqft"],inplace=True)

In [ ]:
df_2

In [ ]:
df_2

In [ ]:
df.insert(5,"price/sqft",df["price"]/df['total_sqft'])

In [ ]:
df

,location,BHK,total_sqft,bath,balcony,price/sqft,price
0,Electronic City Phase II,2,1056.0,2.0,1.000000,3699.810606,3907000.0
1,Chikka Tirupathi,4,2600.0,5.0,3.000000,4615.384615,12000000.0
2,Uttarahalli,3,1440.0,2.0,3.000000,4305.555556,6200000.0
3,Lingadheeranahalli,3,1521.0,3.0,1.000000,6245.890861,9500000.0
4,Kothanur,2,1200.0,2.0,1.000000,4250.000000,5100000.0
...,...,...,...,...,...,...,...
13315,Whitefield,5,3453.0,4.0,0.000000,6689.834926,23100000.0
13316,Richards Town,4,3600.0,5.0,1.584376,11111.111111,40000000.0
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,1.000000,5258.545136,6000000.0
13318,Padmanabhanagar,4,4689.0,4.0,1.000000,10407.336319,48800000.0
13319,Doddathoguru,1,550.0,1.0,1.000000,3090.909091,1700000.0

In [ ]:
from sklearn.datasets import load_breast_cancer
c=load_breast_cancer()

In [ ]:
d={
    "name":"amit",
    "roll":1
}
d

{'name': 'amit', 'roll': 1}

In [ ]:
c.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
c.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
c.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
c.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
c.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
df_c=pd.DataFrame(np.c_[c.data,c.target],columns=list(c.feature_names)+["output"])
df_c

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,output
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0.0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0.0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0.0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0.0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0.0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0.0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0.0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0.0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1.0

In [ ]:
df_c.shape

(569, 31)

In [ ]:
df_c.isnull().sum().sum()

np.int64(0)

In [ ]:
x=df_c.iloc[ : , :-1]

In [ ]:
x.shape

(569, 30)

In [ ]:
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
y=df_c.iloc[ : ,-1]

In [ ]:
y.shape

(569,)

In [ ]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0
Name: output, Length: 569, dtype: float64

In [ ]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a[1:3]

array([2, 3])

array([2, 3])

In [ ]:
a[-5]

np.int64(1)

In [ ]:
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0
Name: output, Length: 569, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train.shape

(455, 30)

In [ ]:
y_train.shape

(455,)

In [ ]:
def area(x,y):
  print(f"area of the room is :{x*y}")

In [ ]:
area(10,12)

area of the room is :120

(10, 10, 120)

In [ ]:
x_test.shape

(114, 30)

In [ ]:
y_test.shape

(114,)

In [ ]:
x_train

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
348,11.470,16.03,73.02,402.7,0.09076,0.05886,0.02587,0.02322,0.1634,0.06372,...,12.51,20.79,79.67,475.8,0.1531,0.1120,0.09823,0.06548,0.2851,0.08763
552,12.770,29.43,81.35,507.9,0.08276,0.04234,0.01997,0.01499,0.1539,0.05637,...,13.87,36.00,88.10,594.7,0.1234,0.1064,0.08653,0.06498,0.2407,0.06484
64,12.680,23.84,82.69,499.0,0.11220,0.12620,0.11280,0.06873,0.1905,0.06590,...,17.09,33.47,111.80,888.3,0.1851,0.4061,0.40240,0.17160,0.3383,0.10310
536,14.270,22.55,93.77,629.8,0.10380,0.11540,0.14630,0.06139,0.1926,0.05982,...,15.29,34.27,104.30,728.3,0.1380,0.2733,0.42340,0.13620,0.2698,0.08351
75,16.070,19.65,104.10,817.7,0.09168,0.08424,0.09769,0.06638,0.1798,0.05391,...,19.77,24.56,128.80,1223.0,0.1500,0.2045,0.28290,0.15200,0.2650,0.06387
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,9.042,18.90,60.07,244.5,0.09968,0.19720,0.19750,0.04908,0.2330,0.08743,...,10.06,23.40,68.62,297.1,0.1221,0.3748,0.46090,0.11450,0.3135,0.10550
476,14.200,20.53,92.41,618.4,0.08931,0.11080,0.05063,0.03058,0.1506,0.06009,...,16.45,27.26,112.10,828.5,0.1153,0.3429,0.25120,0.13390,0.2534,0.07858
336,12.990,14.23,84.08,514.3,0.09462,0.09965,0.03738,0.02098,0.1652,0.07238,...,13.72,16.91,87.38,576.0,0.1142,0.1975,0.14500,0.05850,0.2432,0.10090
42,19.070,24.81,128.30,1104.0,0.09081,0.21900,0.21070,0.09961,0.2310,0.06343,...,24.09,33.17,177.40,1651.0,0.1247,0.7444,0.72420,0.24930,0.4670,0.10380
2,19.690,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.45040,0.24300,0.3613,0.08758

In [ ]:
x_test

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
312,12.760,13.37,82.29,504.1,0.08794,0.07948,0.04052,0.02548,0.1601,0.06140,...,14.190,16.40,92.04,618.8,0.1194,0.22080,0.1769,0.08411,0.2564,0.08253
213,17.420,25.56,114.50,948.0,0.10060,0.11460,0.16820,0.06597,0.1308,0.05866,...,18.070,28.07,120.40,1021.0,0.1243,0.17930,0.2803,0.10990,0.1603,0.06818
114,8.726,15.83,55.84,230.9,0.11500,0.08201,0.04132,0.01924,0.1649,0.07633,...,9.628,19.62,64.48,284.4,0.1724,0.23640,0.2456,0.10500,0.2926,0.10170
40,13.440,21.58,86.18,563.0,0.08162,0.06031,0.03110,0.02031,0.1784,0.05587,...,15.930,30.25,102.50,787.9,0.1094,0.20430,0.2085,0.11120,0.2994,0.07146
176,9.904,18.06,64.60,302.4,0.09699,0.12940,0.13070,0.03716,0.1669,0.08116,...,11.260,24.39,73.07,390.2,0.1301,0.29500,0.3486,0.09910,0.2614,0.11620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,11.890,21.17,76.39,433.8,0.09773,0.08120,0.02555,0.02179,0.2019,0.06290,...,13.050,27.21,85.09,522.9,0.1426,0.21870,0.1164,0.08263,0.3075,0.07351
195,12.910,16.33,82.53,516.4,0.07941,0.05366,0.03873,0.02377,0.1829,0.05667,...,13.880,22.00,90.81,600.6,0.1097,0.15060,0.1764,0.08235,0.3024,0.06949
297,11.760,18.14,75.00,431.1,0.09968,0.05914,0.02685,0.03515,0.1619,0.06287,...,13.360,23.39,85.10,553.6,0.1137,0.07974,0.0612,0.07160,0.1978,0.06915
392,15.490,19.97,102.40,744.7,0.11600,0.15620,0.18910,0.09113,0.1929,0.06744,...,21.200,29.41,142.10,1359.0,0.1681,0.39130,0.5553,0.21210,0.3187,0.10190
329,16.260,21.88,107.50,826.8,0.11650,0.12830,0.17990,0.07981,0.1869,0.06532,...,17.730,25.21,113.70,975.2,0.1426,0.21160,0.3344,0.10470,0.2736,0.07953

In [ ]:
y_train

348    1.0
552    1.0
64     0.0
536    0.0
75     0.0
      ...
318    1.0
476    1.0
336    1.0
42     0.0
2      0.0
Name: output, Length: 455, dtype: float64

In [ ]:
y_test

312    1.0
213    0.0
114    1.0
40     0.0
176    1.0
      ...
415    1.0
195    1.0
297    0.0
392    0.0
329    0.0
Name: output, Length: 114, dtype: float64

In [ ]:
from sklearn.preprocessing import MinMaxScaler , StandardScaler

In [ ]:
STD=StandardScaler()
MM=MinMaxScaler()

In [ ]:
x_train_std=STD.fit_transform(x_train)

In [ ]:
x_train_std

array([[-0.76087652, -0.73245909, -0.78715669, ..., -0.77471789,
        -0.09274063,  0.18302536],
       [-0.3896309 ,  2.28891545, -0.44333642, ..., -0.78235531,
        -0.80573919, -1.1247968 ],
       [-0.41533252,  1.02850622, -0.388028  , ...,  0.8462477 ,
         0.76157295,  1.07078353],
       ...,
       [-0.32680472, -1.13831537, -0.33065583, ..., -0.88133624,
        -0.76559287,  0.94453479],
       [ 1.40948246,  1.24721766,  1.49452211, ...,  2.03310245,
         2.82830524,  1.11095358],
       [ 1.58653806,  0.44452413,  1.56468951, ...,  1.93687098,
         1.13091904,  0.18015607]])

In [ ]:
df_c_sc_std=pd.DataFrame(np.c_[x_train_std],columns=list(c.feature_names))
df_c_sc_std

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,-0.760877,-0.732459,-0.787157,-0.715263,-0.445409,-0.899778,-0.809282,-0.684221,-0.672518,0.092433,...,-0.781829,-0.782020,-0.824339,-0.712583,0.882860,-0.936369,-0.850060,-0.774718,-0.092741,0.183025
1,-0.389631,2.288915,-0.443336,-0.416712,-1.012856,-1.209714,-0.882619,-0.895064,-1.012859,-0.966017,...,-0.500639,1.660850,-0.574288,-0.504061,-0.426124,-0.972024,-0.905638,-0.782355,-0.805739,-1.124797
2,-0.415333,1.028506,-0.388028,-0.441970,1.075350,0.363604,0.271264,0.481697,0.298351,0.406368,...,0.165121,1.254508,0.128702,0.010842,2.293213,0.936186,0.594841,0.846248,0.761573,1.070784
3,0.038729,0.737643,0.069298,-0.070768,0.479531,0.160983,0.687671,0.293654,0.373584,-0.469193,...,-0.207043,1.382995,-0.093763,-0.269759,0.217349,0.090639,0.694598,0.305519,-0.338436,-0.053404
4,0.552762,0.083763,0.495669,0.462480,-0.380152,-0.423617,0.083445,0.421492,-0.084981,-1.320274,...,0.719231,-0.176522,0.632956,0.597825,0.746232,-0.347415,0.027179,0.546861,-0.415517,-1.180461
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,-1.454249,-0.085344,-1.321667,-1.164224,0.187295,1.695653,1.324090,-0.021715,1.820931,3.506837,...,-1.288386,-0.362829,-1.152104,-1.025980,-0.483420,0.736897,0.872734,-0.025945,0.363322,1.208509
451,0.018739,0.282182,0.013164,-0.103121,-0.548259,0.074681,-0.501513,-0.495665,-1.131083,-0.430312,...,0.032796,0.257123,0.137600,-0.094033,-0.783120,0.533787,-0.123405,0.270386,-0.601796,-0.336316
452,-0.326805,-1.138315,-0.330656,-0.398549,-0.171615,-0.134507,-0.666212,-0.741607,-0.608032,1.339533,...,-0.531653,-1.405184,-0.595645,-0.536857,-0.831601,-0.391985,-0.627888,-0.881336,-0.765593,0.944535
453,1.409482,1.247218,1.494522,1.274980,-0.441862,2.104648,1.488167,1.272810,1.749280,0.050671,...,1.612425,1.206325,2.074530,1.348433,-0.368829,3.090165,2.123490,2.033102,2.828305,1.110954
454,1.586538,0.444524,1.564690,1.555935,0.890930,0.995858,1.322847,1.997569,0.885888,-0.444712,...,1.504911,-0.020731,1.335946,1.450151,0.499420,1.053340,0.822856,1.936871,1.130919,0.180156

In [ ]:
x_train_minMax=MM.fit_transform(x_train)

In [ ]:
df_c_sc_mm=pd.DataFrame(np.c_[x_train_minMax],columns=list(c.feature_names))
df_c_sc_mm

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,0.212457,0.213730,0.201990,0.109947,0.344227,0.121097,0.060671,0.121380,0.289899,0.285442,...,0.162931,0.233742,0.145724,0.071422,0.556476,0.093026,0.078458,0.225017,0.253499,0.276280
1,0.273984,0.666892,0.259554,0.154571,0.272005,0.070425,0.046834,0.078359,0.241919,0.129688,...,0.211313,0.639126,0.187709,0.100644,0.354751,0.086876,0.069113,0.223299,0.165977,0.083079
2,0.269724,0.477849,0.268813,0.150795,0.537781,0.327649,0.264540,0.359279,0.426768,0.331638,...,0.325863,0.571695,0.305742,0.172803,0.773823,0.415996,0.321406,0.589691,0.358368,0.407426
3,0.344976,0.434224,0.345380,0.206278,0.461948,0.294522,0.343105,0.320910,0.437374,0.202797,...,0.261829,0.593017,0.268390,0.133479,0.453916,0.270160,0.338179,0.468041,0.223339,0.241353
4,0.430167,0.336152,0.416765,0.285981,0.352532,0.198945,0.229104,0.346994,0.372727,0.077559,...,0.421202,0.334222,0.390408,0.255063,0.535421,0.194606,0.225958,0.522337,0.213877,0.074856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,0.097544,0.310788,0.112501,0.042842,0.424754,0.545427,0.463180,0.256560,0.641414,0.787879,...,0.075774,0.303305,0.090692,0.027502,0.345921,0.381623,0.368131,0.393471,0.309482,0.427772
451,0.341663,0.365911,0.335982,0.201442,0.331137,0.280412,0.118738,0.159854,0.225253,0.208519,...,0.303095,0.406183,0.307236,0.158106,0.299735,0.346592,0.200639,0.460137,0.191011,0.199559
452,0.284396,0.152858,0.278419,0.157285,0.379074,0.246212,0.087664,0.109671,0.298990,0.468955,...,0.205977,0.130330,0.184123,0.096048,0.292264,0.186919,0.115815,0.201031,0.170905,0.388776
453,0.572152,0.510653,0.583996,0.407423,0.344678,0.612294,0.494137,0.520700,0.631313,0.279296,...,0.574884,0.563699,0.632452,0.360254,0.363581,0.787505,0.578435,0.856701,0.612064,0.413360
454,0.601496,0.390260,0.595743,0.449417,0.514309,0.431017,0.462946,0.668583,0.509596,0.206400,...,0.556386,0.360075,0.508442,0.374508,0.497385,0.436202,0.359744,0.835052,0.403706,0.275856

In [ ]:
y_train

348    1.0
552    1.0
64     0.0
536    0.0
75     0.0
      ...
318    1.0
476    1.0
336    1.0
42     0.0
2      0.0
Name: output, Length: 455, dtype: float64